name: Remote Build Claat

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: |
          go get golang.org/x/lint/golint
          # Install protobuf dependencies
          go get -u github.com/golang/protobuf/protoc-gen-go
          curl -OL https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip
          sudo unzip -o protoc-3.7.1-linux-x86_64.zip -d /usr/local bin/protoc
          sudo unzip -o protoc-3.7.1-linux-x86_64.zip -d /usr/local include/*
          rm -f protoc-3.7.1-linux-x86_64.zip
          # Dynamically get rest of Golang-specific dependencies
          go get -t -d ./claat/...
      - run: go generate
        working-directory: ./claat/render
      - run: make
        working-directory: ./claat
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: './claat/bin/claat'
          asset_name: claat
          tag: ${{ github.ref }}
          overwrite: true
          body: "Latest claat tool"