name: Remote Build Claat

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go get github.com/mulesoft-consulting/codelabs-claat-tool/claat
      - run: cd claat/render && go generate
      - run: cd claat && make
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: './claat/bin/claat'
          asset_name: claat
          tag: ${{ github.ref }}
          overwrite: true
          body: "Latest claat tool"